version: "3.8"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  app:
    build: .
    container_name: springboot-app
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      APP_SECRETKEY: ${APP_SECRETKEY}
      STRIPE_SECRETKEY: ${STRIPE_SECRETKEY}
      STRIPE_WEBHOOK: ${STRIPE_WEBHOOK}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
    volumes:
      - springboot-images:/app
    networks:
      - backend

volumes:
  mysql_data:
  springboot-images:

networks:
  backend: