# You don't need them in production
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=admin
spring.security.user.password=demo@123