# You don't need them in production
# It's recommended to use update or create , for testing use create-drop
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.security.user.name=admin
spring.security.user.password=demo@123